import { icon, renderCart } from "../components/ui.js";
import { escapeHtml as e } from "../lib/html.js";
import { deliveryDates, deliverySlots } from "../lib/delivery.js";

function whatsappUrl(number, orderId) {
  const digits = String(number || "").replace(/\D/g, "");
  if (!digits) return "";
  const message = `Hola Snackyzz, quisiera coordinar la entrega de mi pedido ${orderId}.`;
  return `https://wa.me/${digits}?text=${encodeURIComponent(message)}`;
}

export function renderCheckout({ cart, payment, contact = {}, delivery = {}, salesPoints = [], fulfillment, demoCatalog, catalogReady, draft, receipt, receiptPreview, checkoutError, submitting, validatingReceipt }) {
  if (!cart.getCount()) return `<main id="main" class="page-width inner-page centered-page" tabindex="-1">${icon("bag")}<h1>Falta lo más rico.</h1><p>Agrega tus cookies favoritas al carrito para continuar.</p><a href="#shop" class="button button-orange">Elegir mis cookies ${icon("arrow")}</a></main>`;
  const locations = salesPoints.filter((point) => point.active !== false);
  const method = fulfillment?.type || (locations.length ? "pickup" : "uber");
  const selected = locations.find((point) => point.id === fulfillment?.pickupLocationId);
  const dates = deliveryDates(delivery.schedule);
  const slots = fulfillment?.deliveryDate ? deliverySlots({ date: fulfillment.deliveryDate, schedule: delivery.schedule, slotHours: delivery.slotHours, leadHours: delivery.leadHours }) : [];
  return `<main id="main" class="page-width inner-page" tabindex="-1"><a href="#shop" class="back-link">← Volver a las cookies</a><div class="page-heading"><h1>Casi puedes saborearlo.</h1><p>Completa tus datos, elige cómo recibirlo y adjunta tu comprobante.</p></div><ol class="checkout-steps" aria-label="Pasos de tu pedido"><li class="is-complete">${icon("check")} Tu carrito</li><li aria-current="step"><span>2</span> Datos y SINPE</li><li><span>3</span> Pedido recibido</li></ol><div class="checkout-layout"><form id="checkout-form" class="checkout-form"><fieldset ${submitting ? "disabled" : ""}><legend class="sr-only">Datos del pedido</legend>
  <section class="form-section"><h2>¿Para quién es el antojo?</h2><div class="field"><label for="customer-name">Nombre completo</label><input id="customer-name" name="name" autocomplete="name" required maxlength="100" value="${e(draft.name)}" placeholder="Tu nombre y apellido"></div><div class="field"><label for="customer-email">Correo electrónico</label><input id="customer-email" name="email" type="email" autocomplete="email" required maxlength="254" value="${e(draft.email)}" placeholder="tucorreo@ejemplo.com" aria-describedby="email-help"><small id="email-help">Aquí recibirás la confirmación después de revisar tu pago.</small></div><div class="field"><label for="customer-phone">Teléfono <span>(opcional)</span></label><input id="customer-phone" name="phone" type="tel" autocomplete="tel" maxlength="30" value="${e(draft.phone)}" placeholder="8888 8888"></div></section>
  <section class="form-section fulfillment-section"><h2>¿Cómo recibes tu pedido?</h2><div class="fulfillment-options"><label class="choice-card ${method === "pickup" ? "is-selected" : ""}"><input type="radio" name="fulfillmentType" value="pickup" ${method === "pickup" ? "checked" : ""} ${locations.length ? "" : "disabled"}><strong>Retiro</strong><span>Recoge en un punto de Snackyzz.</span></label>${delivery.uberEnabled === false ? "" : `<label class="choice-card ${method === "uber" ? "is-selected" : ""}"><input type="radio" name="fulfillmentType" value="uber" ${method === "uber" ? "checked" : ""}><strong>Enviar con mensajero</strong><span>Recíbelo en la dirección y horario que indiques.</span></label>`}</div>${method === "pickup" ? `<div class="field"><label for="pickup-location">Punto de retiro</label><select id="pickup-location" name="pickupLocationId" required>${locations.length ? `<option value="">Selecciona una ubicación</option>${locations.map((point) => `<option value="${e(point.id)}" ${fulfillment?.pickupLocationId === point.id ? "selected" : ""}>${e(point.name)} — ${e(point.city)}</option>`).join("")}` : `<option value="">No hay puntos disponibles</option>`}</select></div>${selected ? `<div class="location-choice"><strong>${e(selected.name)}</strong><p>${e(selected.address)}, ${e(selected.city)}</p>${selected.hours ? `<span>${e(selected.hours)}</span>` : ""}</div>` : ""}` : `<div class="field"><label for="delivery-address">Dirección de entrega</label><textarea id="delivery-address" name="deliveryAddress" required minlength="8" maxlength="300" rows="3" placeholder="Provincia, cantón, distrito y señas exactas">${e(fulfillment?.deliveryAddress || "")}</textarea></div><div class="product-form-grid"><div class="field"><label for="delivery-date">Fecha de entrega</label><select id="delivery-date" name="deliveryDate" required><option value="">Selecciona una fecha</option>${dates.map((item) => `<option value="${e(item.value)}" ${fulfillment?.deliveryDate === item.value ? "selected" : ""}>${e(item.label)}</option>`).join("")}</select></div><div class="field"><label for="delivery-slot">Horario de entrega</label><select id="delivery-slot" name="deliverySlotStart" required ${fulfillment?.deliveryDate ? "" : "disabled"}><option value="">Selecciona un horario</option>${slots.map((item) => `<option value="${e(item.value)}" ${fulfillment?.deliverySlotStart === item.value ? "selected" : ""}>${e(item.label)}</option>`).join("")}</select></div></div><div class="uber-notice">${icon("pin")}<p>${e(delivery.disclaimer || "El costo del servicio de mensajería corre por cuenta del cliente y se paga por separado.")}</p></div>`}</section>
  <section class="form-section"><h2>Un SINPE y listo.</h2>${payment.configured ? `<p>Realiza la transferencia por <strong>${cart.getFormattedTotal()}</strong> y adjunta una imagen legible del comprobante.</p><div class="sinpe-account"><div><span>SINPE Móvil</span><strong>${e(payment.number)}</strong><p>${e(payment.recipient)}</p></div><button type="button" class="text-button" data-copy-sinpe>Copiar número</button></div>` : `<div class="notice"><strong>${demoCatalog ? "Estás probando Snackyzz." : "El pago aún no está disponible."}</strong><p>${demoCatalog ? "Este es un pedido de prueba. No realices una transferencia real; utiliza una imagen de muestra como comprobante." : "El número SINPE todavía no está configurado. Escríbenos para consultar antes de hacer un pago."}</p></div>`}<label class="upload-zone ${receipt ? "has-file" : ""}" for="receipt"><input type="file" id="receipt" name="receipt" accept="image/jpeg,image/png" ${receipt ? "" : "required"} aria-describedby="receipt-help">${receipt ? `<img class="receipt-preview" src="${e(receiptPreview)}" alt="Vista previa de tu comprobante"><span><strong>${e(receipt.name)}</strong><span>Cambiar imagen ${icon("upload")}</span></span>` : `${icon("upload")}<strong>Sube tu comprobante SINPE</strong><span>Selecciona una imagen desde tu dispositivo</span>`}</label><small id="receipt-help">Obligatorio · JPG o PNG · Máximo 5 MB</small><p class="privacy-note">El comprobante se usa para revisar tu pago y solo está disponible para la administración.</p></section><div class="checkout-message" id="checkout-error" role="alert" ${checkoutError ? "" : "hidden"}>${e(checkoutError)}</div><button type="submit" class="button button-dark wide" ${submitting || validatingReceipt || !catalogReady || (!payment.configured && !demoCatalog) ? "disabled" : ""}>${submitting ? "Registrando tu pedido…" : demoCatalog ? "Registrar pedido de prueba" : "Realizar pedido"} ${submitting ? '<span class="spinner" aria-hidden="true"></span>' : icon("arrow")}</button><p class="checkout-disclaimer">Tu pedido quedará pendiente de revisar el SINPE. Te enviaremos un correo cuando sea confirmado.</p></fieldset></form><div class="cart-column">${renderCart(cart, { checkout: true, fulfillment })}<div class="delivery-note">${icon("mail")}<p>¿Consultas sobre entrega o retiro?<br><a href="mailto:${e(contact.email || "Snackyzz.cookies@gmail.com")}">Escríbenos antes de comprar.</a></p></div></div></div></main>`;
}

export function renderSuccess({ lastOrder, contact = {} }) {
  if (!lastOrder) return `<main id="main" class="page-width inner-page centered-page" tabindex="-1"><h1>Tu próximo antojo te espera.</h1><p>No hay un pedido recién registrado en esta sesión.</p><a href="#shop" class="button button-orange">Ver las cookies ${icon("arrow")}</a></main>`;
  const whatsapp = whatsappUrl(contact.whatsapp, lastOrder.id);
  return `<main id="main" class="page-width success-page" tabindex="-1"><div class="success-mark">${icon("check")}</div><h1>¡Pedido realizado<br>con éxito!</h1><p>Tu antojo ya está en nuestras manos.</p><div class="success-receipt"><div><span>Número de pedido</span><strong>${e(lastOrder.id)}</strong></div><div><span>Estado</span><span class="status pending">${icon("clock")} Pendiente de revisión</span></div><p>Una vez revisado el SINPE, te mandaremos un correo con la confirmación de tu pedido a <strong>${e(lastOrder.email)}</strong>.</p>${lastOrder.demo ? '<p class="demo-notice">Este es un pedido de prueba.</p>' : ""}</div>${whatsapp ? `<a href="${e(whatsapp)}" target="_blank" rel="noopener noreferrer" class="button button-dark">Contactar por WhatsApp ${icon("arrow")}</a>` : ""}<a href="#shop" class="button button-orange">Volver a las cookies ${icon("arrow")}</a><a href="mailto:${e(contact.email || "Snackyzz.cookies@gmail.com")}" class="text-link">¿Necesitas ayuda? Escríbenos</a></main>`;
}
